{
	"ProjectName": "ExampleProjectName",
	"diagrams": [
		"/home/sheep1.duml",
		"/home/sheep3.duml",
		"/home/sheep2.duml",
		"/home/sheep4.duml",
		"/home/sheep5.duml",
		"/home/sheep6.duml",
		"/home/sheep7.duml",
		"/home/sheep8.duml",
		"/home/sheep9.duml",
		"/home/sheep10.duml",
		"/home/sheep11.duml",
		"/home/sheep12.duml"
	]
}
