@startuml
autonumber
 -> ":UMLProject": openProject(projectName)
opt#gold #white
     -> ":UMLProject": selectDiagram(diagramName)
end
opt#gold #white
     -> ":UMLProject": addGadget(gadgetType, point)
end
opt#gold #white
     -> ":UMLProject": selectComponent(point)
 end
 opt#gold #white
    -> ":UMLProject": addAssociation(AssociationType)
 end
 opt#gold #white
    -> ":UMLProject": startDragging(point)
 end
 opt#gold #white
    -> ":UMLProject": stopDragging(point)
 end
 opt#gold #white
     -> ":UMLProject": unselectAllComponents()
 end
 opt#gold #white
     -> ":UMLProject": selectComponent(point)
 end
 opt#gold #white
     -> ":UMLProject": editAttribute(attributeName, newValue)
 end
@enduml
